### ISSUE TITLE
App crashes with the provided MainActivity.kt 

### ISSUE THREAD

**Issue by O-Hannonen** [wiseminds/userleap_flutter#3]
App crashes when using the example MainAcitivity.kt provided in the documentation. The example file is missing package on the first line. This MainActivity.kt is working (when [your.package] is replaced with your own package name): 

```
package com.[your.package]
import android.os.Bundle
import androidx.annotation.NonNull
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.plugins.GeneratedPluginRegistrant


class MainActivity: FlutterFragmentActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
    }
}
```

Also the documentation should probably include an example MainActivity.java, for those using java in their flutter project.

**Comment by wiseminds** [comment]
can I see a detailed log of the issue ?

**Comment by O-Hannonen** [comment]
Here are the logs when running with the broken MainActivity.kt:
```
Launching lib/main.dart on IN2023 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         5.9s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...              2,881ms
E/AndroidRuntime(13307): FATAL EXCEPTION: main
E/AndroidRuntime(13307): Process: com.example.userleap_test, PID: 13307
E/AndroidRuntime(13307): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.userleap_test/com.example.userleap_test.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.userleap_test.MainActivity" on path: DexPathList[[zip file "/data/app/~~BbJjLY9LmNFGoAaYQMrD_Q==/com.example.userleap_test-Hz8U036uHoQj7OsbpKjZRA==/base.apk"],nativeLibraryDirectories=[/data/app/~~BbJjLY9LmNFGoAaYQMrD_Q==/com.example.userleap_test-Hz8U036uHoQj7OsbpKjZRA==/lib/arm64, /data/app/~~BbJjLY9LmNFGoAaYQMrD_Q==/com.example.userleap_test-Hz8U036uHoQj7OsbpKjZRA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(13307):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3527)
E/AndroidRuntime(13307):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
E/AndroidRuntime(13307):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(13307):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(13307):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(13307):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
E/AndroidRuntime(13307):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(13307):        at android.os.Looper.loop(Looper.java:233)
E/AndroidRuntime(13307):        at android.app.ActivityThread.main(ActivityThread.java:8010)
E/AndroidRuntime(13307):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13307):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
E/AndroidRuntime(13307):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
E/AndroidRuntime(13307): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.userleap_test.MainActivity" on path: DexPathList[[zip file "/data/app/~~BbJjLY9LmNFGoAaYQMrD_Q==/com.example.userleap_test-Hz8U036uHoQj7OsbpKjZRA==/base.apk"],nativeLibraryDirectories=[/data/app/~~BbJjLY9LmNFGoAaYQMrD_Q==/com.example.userleap_test-Hz8U036uHoQj7OsbpKjZRA==/lib/arm64, /data/app/~~BbJjLY9LmNFGoAaYQMrD_Q==/com.example.userleap_test-Hz8U036uHoQj7OsbpKjZRA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(13307):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(13307):        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(13307):        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(13307):        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
E/AndroidRuntime(13307):        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
E/AndroidRuntime(13307):        at android.app.Instrumentation.newActivity(Instrumentation.java:1273)
E/AndroidRuntime(13307):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3515)
E/AndroidRuntime(13307):        ... 11 more
```

You can also reproduce it:
1. `flutter create test`
2. Copy MainActivity.kt from the documentation
3. Add java 8 support 
4. Run the app

**Comment by wiseminds** [comment]
Kindly confirm you followed the documentation on pub.dev.



```  android {
    ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    // For Kotlin projects
    kotlinOptions {
        jvmTarget = "1.8"
    }
```

make sure you added the above in your app/build.gradle

**Comment by O-Hannonen** [comment]
Yes I have added those to the app level build.gradle. I don't think that's the issue, since the app starts working when I add package name to MainActivity.kt.

**Comment by wiseminds** [comment]
That means it works now ?

**Comment by O-Hannonen** [comment]
Yes, I figured it out and it is working now. I just think that the documentation should be updated with a working example of a MainActivity.kt file if someone else is facing the same issue.

**Comment by wiseminds** [comment]
I think I am missing what the issue is here, the example project works. 

The issue you have is that you copied the example project and did not change the package name to that of your project.

if you want to copy MainActivity.kt, you have to make sure you updated the package name to that of your project.

an easy way to see your package name is to check your app/build.gradle and check for `applicationId`

**Comment by O-Hannonen** [comment]
I have not copied any example project. I just copied the few necessary lines from the documentation.

The issue is, that the example MainActivity.kt file in the readme section of the flutter package in [pub.dev](https://pub.dev/packages/userleap_flutter) does not contain this line:
`package com.[your.package]`

Without that line, the app won't work and it crashes. Similarly the [documentation](https://pub.dev/documentation/userleap_flutter/latest/) does not contain that line. If someone (like me) just copies and pastes the given MainActivity.kt, the app will crash. The documentation should be updated to include the package name.

**Comment by wiseminds** [comment]
ok thanks I will update the readme,
